Create UI
tricore-as11/InternshipGame1 pull request #11
Opened 2023-06-21 06:13 UTC by tricore-as11

実際のゲームシーンで使うUIの画像とUIを動かすためのScriptとPrefabを追加しました
追加したUI↓
・体力ゲージ
・今のステージが何ステージ化わかるようにするUI

2023-06-21 07:06 UTC, tricore-as05 requested changes
スクリプト側の変更とアセット追加を一緒におこなうと変更ファイルがかなり多くなり、
レビューする画面がかなり重くなるので、次からはアセット追加とわけるようにしてください
(プレハブや画像類は一緒にしても大丈夫です)

2023-06-21 07:06 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeGreen.cs
> +public class HPGaugeGreen : MonoBehaviour
[MUST]
ゲージが分かれているのはいいんですが、状態管理がバラバラになっているので、
親クラスを用意してイベント発行や状態管理を行い、それぞれのゲージは見た目の更新のみ行う形に修正してください

2023-06-21 07:06 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +        image.sprite = iconList[(int)type];
[MUST]
画像類を見たところ、
それぞれのステージ状況に応じた固定の画像を用意しているようですが、その設計はやめましょう

バラ画像(赤丸、青丸、黒丸)を1つずつ用意し、それぞれ状態によって画像を切り替えていくようにしてください
そうすることで後にステージを追加した時に自動でアイコンが増えるような設計が可能になります

2023-06-22 01:06 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +    static readonly float DecreaseSpeed = 100.0f; // HPゲージが減るスピード(大きければ大きいほど遅い)
修正しました

2023-06-22 01:08 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +    float futureHP = 1.0f; // この数値までHPが減る
大石さんの考えで設計をやり直せたと思います

2023-06-22 01:09 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeGreen.cs
> +        image.fillAmount -= damage;
修正しました

2023-06-22 01:09 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +        while (image.fillAmount >= futureHP)
修正しました

2023-06-22 01:10 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeGreen.cs
> +public class HPGaugeGreen : MonoBehaviour
修正しました

2023-06-23 03:01 UTC, tricore-as11 commented
@tricore-as05 修正しました
レビューお願いします

2023-06-23 03:01 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +        image.sprite = iconList[(int)type];
修正しました

2023-06-23 03:02 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerString.cs
> +public class StageTrackerString : MonoBehaviour
今後ピンに機能を追加する可能性があるので分けたまま実装したいと思っています

2023-06-23 03:04 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +        posXList.Add(0.0f);
posXList自体がHorizontalLayoutGroupによって必要なくなりました

2023-06-23 03:05 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +    [SerializeField] float adjustmentRange = 3.0f; // 振れ幅の調整(大きいほうが揺れ幅が小さくなる)
それらの変数はAnimatorを使用することによって必要なくなりました

2023-06-23 03:05 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeGreen.cs
> +        return image.fillAmount < CalculationError;
hpをint型にすることによって解決しました

2023-06-23 03:40 UTC, tricore-as05 requested changes
stage1.pngなど不要になった画像類などがあるはずなのでそちらを消してください

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +        prevHP = hp = maxHP;
[MUST]
不要なStartなどは消してください
InitializeMaxHPのタイミングでこの処理を行えばいいはずです

タイミングが同じものはできる限り一緒に読んで、StartやUpdateなどをできる限り少なくするようにしてください
(ただその為だけに無駄に参照をもってしまうのは良くない)

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +    bool CheckDie()
[IMO]
関数化は、個人的に共通部分や1つの関数にまとめると肥大化するから分けたい場合などにすると考えており、
CheckDie()やSetHP()などは別に分ける必要ないのではと思ってしまいます。
何か意図とかありますか？

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +    enum PrefabType
[MUST]
こういった場合はできれば動作基準で命名してほしいです。
「PrefabTypeがRedだから現ステージ」ではなく、「現ステージ(例: StageProgressTypeがInProgress)だからアイコンは赤」というイメージで考えるといいかもしれません

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +                typeList.Add(PrefabType.Arrow);
[IMO]
矢印はアイコンに含めないで、
アイコン切り替えとは別でオブジェクトを用意しておき、次のステージがある場合に表示状態にするようにしてほしいです。

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +    [SerializeField] float forwardPosX = 27.0f; // pinを次の場所に進める距離
[MUST]
初期化時に指定の位置に設定するような処理を追加したほうがいいと思います
ある程度ステージをクリアしてピンが進んだあとに、ゲームオーバーになって最初からになった際のピンの初期位置への移動などがしやすくなるはずです。
位置のリセットという考えでもいいかもしれません

2023-06-23 03:40 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +    public void Next()
[IMO]
引数に指定の座標を設定してもらう形の方がいいと思います
アイコンの位置を設定しなおすたびにforwardPosXの値を変える必要はないですし、平行移動ではなく斜め移動(縦の移動も追加)を後からやりたいってなった場合でも追加しやすいです。

2023-06-23 04:07 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +    bool CheckDie()
機能で分けれるものは分けていました
修正します

2023-06-23 04:08 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/HPGaugeRed.cs
> +        prevHP = hp = maxHP;
修正します

2023-06-23 04:10 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +    enum PrefabType
修正します

2023-06-23 04:11 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +                typeList.Add(PrefabType.Arrow);
修正します

2023-06-23 04:11 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +    [SerializeField] float forwardPosX = 27.0f; // pinを次の場所に進める距離
修正します

2023-06-23 04:12 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerPin.cs
> +    public void Next()
修正します

2023-06-23 06:22 UTC, tricore-as11 commented
@tricore-as05 
修正お願いします

2023-06-23 07:16 UTC, tricore-as05 requested changes

2023-06-23 07:16 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +        SetupTypeList(nowStageNum, maxStageNum);
[MUST]
矢印を消す機能はアイコン側でやるべきです。
生成クラスで、生成物自体をいじくるのはやめましょう

2023-06-26 02:10 UTC, tricore-as11 commented
@tricore-as05 
修正しました
レビューお願いします

2023-06-26 02:36 UTC, tricore-as05 requested changes

2023-06-26 02:36 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/StageTrackerIcon.cs
> +            imageList[(int)ImageType.children].enabled = false;
[MUST]
同じImageとはいえ、矢印とアイコンでは表示する意味が違うので、
Listにまとめずに個々て参照を持ってほしいです

2023-06-26 02:48 UTC, tricore-as11 commented
@tricore-as05 
StageTrackerIconクラスのImageコンポーネントをListでまとめていたところを
個々に参照を持つように変更しました
レビューお願いします

2023-06-26 03:04 UTC, tricore-as05 approved these changes
LGTM

2023-06-26 03:06 UTC, merged