Create Arrow
tricore-as11/InternshipGame1 pull request #8
Opened 2023-06-15 06:00 UTC by tricore-as11

Arrow関連のクラスの実装を行いました
Arrowクラス：Arrow本体
ArrowInstanceReserverクラス：矢のインスタンスをステージごとに保持するクラス
ArrowSpawnerクラス：Arrowを一つずつStageStateMachineクラスに渡すクラス
StageStateMachineクラスはステージの状態を管理するクラスでまだ実装していないので
Sampleをつくって動かしています

2023-06-15 06:29 UTC, tricore-as05 requested changes
ArrowSpawnerとArrowInstanceReserverの関係性がぐちゃぐちゃになっているので後で口頭で説明します。

イメージとしては下記です
ArrowSpawner : ただ命令があればArrowを生成するだけのクラス
ArrowInstanceReserver : 生成されたArrow達を管理し、命令があれば発射や削除のイベントを矢に出す
　　　　　　　　　　   名前もArrowGroupみたいなシンプルな名前でいいです

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    static readonly int HitSE = 0; // Targetと衝突した時のSE
[IMO]
SEの種類とかenumで定義してほしいですね

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        hitEffect.Play(this.transform.position);
[nits]
今回は一旦大丈夫ですが、後ほどやってほしいことがあります。
SE再生用のクラスを作って、そのクラスのPlay関数を呼べば指定のSEが再生されるようなクラスを作ってほしいです。
(例としては SePlayer.Play(SeType.ArrowHit); で再生を呼び出せるみたいな)

なぜこの仕組みにしてほしいかというと、音の追加や削除など設定追加しやすい形になるためです。

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    private void OnTriggerEnter2D(Collider2D other)
[MUST]
UnityのReflection依存の関数(Start, Update, OnTrigger~)などは上の方に固めて定義してほしいです。
自分で作った関数ではなくUnityに元々用意されている関数などですね

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        audioSource = GetComponent<AudioSource>();
[Q]
わざわざGetComponentで取得した理由はありますか？
確かSerializeFieldで取得できたかと思いますが

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        if (isShoot)
[MUST]
コルーチンとかって使ったことありますか？
Updateを使わずにある条件下の間だけUpdateみたいに毎フレーム処理を回せるみたいな機能があるので、
Updateを使わずにコルーチンで移動をやってみてほしいです

2023-06-15 06:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/HitEffect.cs
> +    private ParticleSystem particleSystem; // particleSystem
ここも

> [Q]
わざわざGetComponentで取得した理由はありますか？
確かSerializeFieldで取得できたかと思いますが

2023-06-15 06:55 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        hitEffect.Play(this.transform.position);
承知しました

2023-06-15 07:02 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    private void OnTriggerEnter2D(Collider2D other)
修正しました

2023-06-15 07:07 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        audioSource = GetComponent<AudioSource>();
修正しました

2023-06-15 07:12 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/HitEffect.cs
> +    private ParticleSystem particleSystem; // particleSystem
修正しました

2023-06-15 07:59 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        if (isShoot)
修正しました

2023-06-15 09:37 UTC, tricore-as03 requested changes

2023-06-16 01:06 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    void Update()
アクセス指定子はつけない方向で統一します

2023-06-16 01:07 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        hitEffect = Instantiate(hitEffectPrefab).GetComponent<HitEffect>();
修正しました

2023-06-16 01:40 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    // 以下衝突した際の挙動
このコメントを削除しました

2023-06-16 02:25 UTC, tricore-as11 commented
修正しました
確認お願いします

2023-06-16 02:26 UTC, tricore-as11 commented
以下変更点です
ArrowGroupの仕様変更
ArrowSpawnerの仕様変更
private指定子の削除
Reflection依存の関数を下にまとめるように変更
HitEffectが再生後Destroyされない問題を解決

2023-06-16 02:51 UTC, tricore-as11 commented
// 定数
や
// メンバ変数
などのコメントも区切るように今から変更します

2023-06-16 03:03 UTC, tricore-as11 commented
// 変数
などを
/*-------
    変数
   -------*/
に変更しました

2023-06-16 03:05 UTC, tricore-as05 requested changes

2023-06-16 03:05 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowGroup.cs
> +            // TODO:通知クラスにインスタンスを渡し切ったことを通知
[MUST]
テスト用の実装は、それらを1つの関数にまとめてそれを呼び出すようにしてください
必要な処理とごちゃ混ぜになってしまうのを防ぎたいです

2023-06-16 03:11 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +    enum SEKind
SEKindの命名をSETypeに変更しました

2023-06-16 03:24 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        isShoot = true;
@tricore-as05 
修正しました

2023-06-16 03:28 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/Arrow.cs
> +        hitEffect = Instantiate(hitEffectPrefab).GetComponent<HitEffect>();
@tricore-as03 
修正しました
以後コメントをしっかり読むよう気を付けます

2023-06-16 03:33 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowSpawner.cs
> +        arrowInstanceList = new List<Arrow>();
@tricore-as05 
修正しました

2023-06-16 03:35 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowSpawner.cs
> +    public void ReserveArrowInstance(int numberOfInstances, Transform transform)
@tricore-as05 
修正しました

2023-06-16 03:42 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowGroup.cs
> +            // TODO:通知クラスにインスタンスを渡し切ったことを通知
@tricore-as05 
修正しました

2023-06-16 03:44 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowSpawner.cs
> +    public void ClearArrowInstance()
@tricore-as05 
修正しました

2023-06-16 03:52 UTC, tricore-as03 approved these changes
LGTM

2023-06-16 04:05 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowGroup.cs
> +            // TODO:通知クラスにインスタンスを渡し切ったことを通知
修正しました

2023-06-16 04:05 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowSpawner.cs
> +    public void ClearArrowInstance()
修正しました

2023-06-16 04:05 UTC, tricore-as11 commented on Assets/MyGameAssets/Scripts/Arrow/ArrowSpawner.cs
> +        return arrowInstanceList;
修正しました

2023-06-16 04:06 UTC, tricore-as11 commented
@tricore-as05 
すべて修正しましたので確認お願いします

2023-06-16 04:24 UTC, tricore-as05 approved these changes
LGTM

2023-06-16 05:09 UTC, merged